[package]
name = "aegis-vault"
version = "0.2.0"
edition = "2021"

[dependencies]
# GUI
eframe         = { version = "0.27", features = ["default"] }
egui           = "0.27"
egui_extras    = { version = "0.27", features = ["image"] }
image          = { version = "0.24", default-features = false, features = ["jpeg", "png", "webp", "gif"] }

# Kriptografi
aes            = "0.8"
argon2         = "0.5"
hmac           = "0.12"
sha2           = "0.10"
rand           = "0.8"
hex            = "0.4"
zeroize        = "1.7"

# Database
rusqlite       = { version = "0.31", features = ["bundled"] }

# File dialog
rfd            = "0.14"

# UUID
uuid           = { version = "1.8", features = ["v4"] }

# TOTP (2FA)
sha1           = "0.10"
data-encoding  = "2.6"
qrcode         = "0.14"
sysinfo = "0.30"
chrono = "0.4"

[profile.release]
opt-level     = 3
lto           = true
codegen-units = 1
strip         = true

[package.metadata.android]
apk_label = "Aegis Vault"
target_sdk_version = 33
min_sdk_version = 24
