[package]
name = "aegis-vault"
version = "0.2.0"
edition = "2021"

[lib]
name = "aegis_vault"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
# GUI
eframe         = "0.29.1"
egui           = "0.29.1"
    egui_extras    = { version = "0.29.1", features = ["image"] }
image          = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp", "gif"] }


# Kriptografi
aes            = "0.8"
argon2         = "0.5"
hmac           = "0.12"
sha2           = "0.10"
rand           = "0.8"
hex            = "0.4"
zeroize        = "1.7"

# Database
rusqlite       = { version = "0.31", features = ["bundled"] }

# Kompresi Folder
zip            = { version = "0.6", default-features = false, features = ["deflate"] }

# UUID
uuid           = { version = "1.8", features = ["v4"] }

# TOTP (2FA)
sha1           = "0.10"
data-encoding  = "2.6"
qrcode         = "0.14"
sysinfo = "0.30"
chrono = "0.4"
libc = "0.2"


[target.'cfg(not(target_os = "android"))'.dependencies]
rfd = "0.14"

[target.'cfg(target_os = "android")'.dependencies]
eframe         = { version = "0.29.1", features = ["default", "android-native-activity"] }
android-activity = "0.6.0"
winit = { version = "0.30", features = ["android-native-activity"] }
android_logger = "0.13"
log = "0.4"
jni = "0.21"
ndk-context = "0.1"

[profile.release]
opt-level     = "z"
lto           = true
codegen-units = 1
strip         = true

[package.metadata.android]
apk_label = "Vault Defender"
target_sdk_version = 33
min_sdk_version = 24
icon = "assets/logo.png"

# Gunakan debug keystore untuk signing rilis sementara
[package.metadata.android.application_attributes]
"android:theme" = "@android:style/Theme.DeviceDefault.NoActionBar"

[package.metadata.android.activity_attributes]
"android:windowSoftInputMode" = "adjustResize"

[package.metadata.android.signing.release]
path = "C:/Users/alama/.android/debug.keystore"
keystore_password = "android"
key_password = "android"
key_alias = "androiddebugkey"

[[package.metadata.android.uses_permission]]
name = "android.permission.READ_EXTERNAL_STORAGE"
[[package.metadata.android.uses_permission]]
name = "android.permission.WRITE_EXTERNAL_STORAGE"
[[package.metadata.android.uses_permission]]
name = "android.permission.MANAGE_EXTERNAL_STORAGE"

# [patch.crates-io]
# android-activity = { path = "third_party/android-activity-0.5.2" }
# ndk = { path = "third_party/ndk-0.8.0" }
